# This file was generated by GoReleaser. DO NOT EDIT.
cask "airplan" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6e4eb1ceae910059a973b5fe859fa019ae6ab3716be899f4c110d367cdc0aa11"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e11befe16d3b30d2ca7eeb0f3646e954e96b23f1643dce1e796787a28c911633"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "927888e68aff153cd4352cba8c8f4d73c2c23080916eb2878cf3cbca2d89a05b"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f1e33db0a6fa799ead3043215fb346975ea5bd9385a1a8ec30cefd29053deab"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "airplan"
  desc "Upload plan documents to S3-compatible storage and print a shareable unguessable URL"
  homepage "https://github.com/jimeh/airplan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "airplan"

  # No zap stanza required

end
