# This file was generated by GoReleaser. DO NOT EDIT.
cask "airplan" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "023b119a8ad1108592fdaa5a2bd2b36e8a0a103919ee3894acff327121c6d288"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac8412f7b7964ab1d4e8d829a34af2179ccef11077370c59dc1aad3f6c759fe5"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca4a56cdd82eaaec17ff9e7b258d9429b8843947f00178202ee848298c85c16d"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f43571ac78ddd68057e9ef9f71ae7dd526d766d20fe282fb9e6ded8955f46080"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "airplan"
  desc "Upload plan documents to S3-compatible storage and print a shareable unguessable URL"
  homepage "https://github.com/jimeh/airplan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "airplan"

  # No zap stanza required

end
