# This file was generated by GoReleaser. DO NOT EDIT.
cask "airplan" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "136574f05377c13e8666bdd4309453d041356b0f88b967129feab0a2f582938c"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de33397371c64e10d64f7be71f57994ba35b6e3e1e13fffc4d9b828d3d88c8fe"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "207ecfbfb0bbcb56f84d022d1849ecfffaf3089e3d77e1134593eb7bf39bcbcb"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e23be4a3e3bc207eb1895e356741ccec04f1780afc310cfe978f56f2d68f7822"
      url "https://github.com/jimeh/airplan/releases/download/v#{version}/airplan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "airplan"
  desc "Upload plan documents to S3-compatible storage and print a shareable unguessable URL"
  homepage "https://github.com/jimeh/airplan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "airplan"

  # No zap stanza required

end
